modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "https://github.com/starfish-studios/One-More-Furniture?tab=License-1-ov-file#readme"

[[mods]]
modId = "yaf"
version = "${version}"
displayName = "Yet Another Furniture"
authors = "Starfish Studios : crispytwig, MrSterner, thelamb_"
description = '''There are furniture mods, then there are more- then we made ANOTHER, but this time, it's YET ANOTHER. How many more furniture mods can we make? Find out in the next episode of \"Furniture Mods\".'''
#logoFile = ""

[[dependencies.yaf]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.yaf]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.yaf]]
modId = "architectury"
mandatory = true
versionRange = "[9.1.12,)"
ordering = "AFTER"
side = "BOTH"