modLoader = "javafml"
loaderVersion = "[5.5.0,)"
#issueTrackerURL = ""
license = "https://github.com/starfish-studios/One-More-Furniture?tab=License-1-ov-file#readme"

[[mods]]
modId = "yaf"
version = "${version}"
displayName = "Yet Another Furniture"
authors = "Starfish Studios : crispytwig, MrSterner, thelamb_"
description = '''There are furniture mods, then there are more- then we made ANOTHER, but this time, it's YET ANOTHER. How many more furniture mods can we make? Find out in the next episode of \"Furniture Mods\".'''
#logoFile = ""

[[dependencies.yaf]]
modId = "neoforge"
type="required"
versionRange="[21.1.55,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.yaf]]
modId = "minecraft"
type="required"
versionRange="[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.yaf]]
modId = "architectury"
type="required"
versionRange = "[13.0.6,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config="yaf.mixins.json"
[[mixins]]
config="yaf-common.mixins.json"